
print("A PROGRAM TO DEMONSTRATE ALL FUNCTIONS / METHODS OF STRINGs ")
ad=(input("PLEASE ENTER YOUR ADDRESS:"))
print("CAPITALIZED STRING IS",ad.capitalize())
print("NAGAR IS AT",ad.find("a",0))
print("ALPHANUMERIC:",ad.isalnum())
print("ALPHABATIC:",ad.isalpha())
print("DIGIT:",ad.isdigit())
print("IS IN LOWER CASE",ad.islower())
print("HAS SPACE:",ad.isspace())
print("IS IN UPPER CASE:",ad.isupper())
print("LOWER CASE IS",ad.lower())
print("UPPER CASE IS",ad.upper())
print("",ad.lstrip('mit'))
print("",ad.rstrip('gar'))
